version: '3.6'
services:
  nightfall_dlp_build:
    image: builder
    build:
      context: .
      target: builder
    environment:
      GO_ENV: ci
    command: ./nightfall_dlp

  nightfall_dlp:
    build:
      context: .
    image: nightfall_dlp

  wait:
    image: deliveroo/circleci:0.2.8
